remove.packages("rlang")
install.packages("rlang")
library(rlang)
install.packages("DBI")
library(DBI)
install.packages("RSQLite")
library(RSQLite)
install.packages("dplyr")
library(dplyr)
# a)
q4db <- dbConnect(SQLite(),"Q4.sqlite")
dbListTables(q4db)
dbGetQuery(q4db, "create table student(roll int primary key,
name varchar2(20), course varchar2(20))")
dbListTables(q4db)
# b)
dbGetQuery(q4db, "insert into student values(1, 'Siddhant', 'BSc') ")
dbGetQuery(q4db, "insert into student values(2, 'Smaran', 'BSc') ")
dbGetQuery(q4db, "insert into student values(3, 'Uday', 'BSc') ")
dbGetQuery(q4db, "insert into student values(4, 'Mahima', 'BSc') ")
dbGetQuery(q4db, "insert into student values(5, 'Alquab', 'BSc') ")
# c)
dbGetQuery(q4db, "select * from student")
# d)
dbGetQuery(q4db, "delete from student")
# e)
dbGetQuery(q4db, "drop table student")
dbDisconnect(q4db)

